services:
  #Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypesoft-frontend
    ports:
     - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    networks:
      - hypesoft-network

  # API .NET
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypesoft-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__MongoDb=${ConnectionStrings__MongoDb}
      - ConnectionStrings__DatabaseName=${ConnectionStrings__DatabaseName}
      - DISABLE_AUTH=${DISABLE_AUTH}
      - KEYCLOAK_INTERNAL_URL=http://keycloak:8080/realms/hypesoft-realm
      - KEYCLOAK_EXTERNAL_URL=http://localhost:8080/realms/hypesoft-realm
      - KEYCLOAK_AUDIENCE=account
    depends_on:
      - mongodb
      - keycloak
    networks:
      - hypesoft-network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: hypesoft-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - hypesoft-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/hypesoft_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express (UI)
  mongo-express:
    image: mongo-express:latest
    container_name: hypesoft-mongo-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH=${ME_CONFIG_BASICAUTH}
    depends_on:
      - mongodb
    networks:
      - hypesoft-network

  # Keycloak Authentication Server
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: hypesoft-keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - KC_PROXY_HEADERS=${KC_PROXY_HEADERS}
    networks:
      - hypesoft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 3s
      retries: 5

      

volumes:
  mongo-data:

networks:
  hypesoft-network:
    driver: bridge